### ISSUE TITLE
Use frontmatter to customize layouts and includes

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#13]
Currently the layouts and includes use the name of their files to be referenced. And additional arguments can't be included in these files. Make it so that every template and include could have additional data like:

```
---
title: head
description: this layout is used to render the head element
var1: any data that can be referenced somewhere
---
```

**Comment by ahmednawar** [comment]
For the template variables such as `var1` from your example, will they only be referenced in the template page itself?

**Comment by dvidsilva** [comment]
Yes, something like that, it can be `{{layout.var1}}` or `{{template.var1}}`

I'm not super  clear about it, so I welcome your proposals.

**Comment by ahmednawar** [comment]
sounds good. Also, do you know if there is a way right now to know which partials are included in a page (w/o having to parse the page for liquid tags)? I looked yesterday but didn't find anything useful.

**Comment by ahmednawar** [comment]
#99 handles this one. Should it be closed?

**Comment by dvidsilva** [comment]
Yes, gonna add the comment from there here.

> This change allows accessing variables defined in layouts' and includes' frontmatters. This could be achieved through the following syntax. {{ page.g.layout.var1}} for accessing layout variables or
{{ page.g.head.var1}} for accessing includes' (hbs partials) variables. head here is the name of the include. g (short for gloria) acts as a namespace to avoid collision between common variable names like 'title' or 'description'.

**Comment by dvidsilva** [comment]
I didn't check, does this only add the information from the partials included in the file? or from every partial?

**Comment by ahmednawar** [comment]
only the ones included in the file
