### ISSUE TITLE
Serve command should probably watch for changes

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#14]

**Comment by dvidsilva** [comment]
I tried some things but I'm going into an infinite loop or failing. So postponing this.

This looks promising tho https://github.com/paulmillr/chokidar

**Comment by mjhea0** [comment]
+1 for chokidar. Pretty easy to set up. I would probably add a new file to manage the auto reload - e.g., "https://github.com/gloriajs/gloria/blob/master/lib/commands/watch.js"

**Comment by dvidsilva** [comment]
Sent a pull request #50
