### ISSUE TITLE
Replace console.log with better logger

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#2]
Console.log is not super easy to test. Better to use something else. 

Probably the same for promp.

**Comment by IAmAnubhavSaini** [comment]
Now, we need to implement a Logging Implementation so that we can `new Logger(implementation)` it.

**Comment by dvidsilva** [comment]
Sweet, anything you recommend? It would be nice to have something that lets us control verbosity too.

**Comment by IAmAnubhavSaini** [comment]
Let me try it with `console` first.

**Comment by mjhea0** [comment]
Winston. http://thisdavej.com/using-winston-a-versatile-logging-library-for-node-js/

**Comment by IAmAnubhavSaini** [comment]
I think verbosity settings are overrated. Think about it case by case.
Case `Everything is fine`: You don't want to log anything really.
Case `Errors`: log information available as error and possibly dump stacks.
Case `in between`: meh.

**Comment by IAmAnubhavSaini** [comment]
@mjhea0 Implement in such a way that we can switch it with new logging library with one swap. Raise PR.

**Comment by dvidsilva** [comment]
Still using console.log but created an utility file to help manage the methods better.
