### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#22]

**Comment by dvidsilva** [comment]
<img width="455" alt="screen shot 2016-11-22 at 7 43 58 pm" src="https://cloud.githubusercontent.com/assets/1588753/20550577/09e0b80a-b0ec-11e6-80f1-f282f8427f13.png">

What about this one?

**Comment by kevdez** [comment]
When I think of "gloria" I think of like a ray of sunlight, with angels singing, or something. 

<img src="https://upload.wikimedia.org/wikipedia/commons/0/03/Angel_from_The_Song_of_Bethlehem.jpg" />

**Comment by dvidsilva** [comment]
Amazing idea, I'll try something with that :P I just thought it would be super funny to copy google.

**Comment by dvidsilva** [comment]
<img width="570" alt="screen shot 2016-11-22 at 7 55 49 pm" src="https://cloud.githubusercontent.com/assets/1588753/20550742/b15f5bf8-b0ed-11e6-9fa6-339198e8170e.png">

**Comment by dvidsilva** [comment]
<img width="579" alt="screen shot 2016-11-22 at 7 57 36 pm" src="https://cloud.githubusercontent.com/assets/1588753/20550795/244cf0f8-b0ee-11e6-9acf-5b90814cdfae.png">

**Comment by kevdez** [comment]
LOL 😆

When I image searched "glory" a bunch of clouds and sunset images popped up.

Maybe you can ask some designers for some input.

Should it be "GloriaJS" or "Gloria.js"? Or just "Gloria"?

**Comment by dvidsilva** [comment]
yes, I think of this https://www.youtube.com/watch?v=zhhYIZJj6rk

I prefer calling it just gloria, but gloria.com was taken so I had to buy gloriajs. However I'm open to ideas. Reaching out to a designer friend to see if she can help us out. But maybe someone in the slack wants to volunteer too.

**Comment by daliaicedo** [comment]
![glorialogo1](https://cloud.githubusercontent.com/assets/11223564/20555186/742a6f8e-b115-11e6-9ba3-1b91f347773e.jpg)

**Comment by daliaicedo** [comment]
![glorialogo2](https://cloud.githubusercontent.com/assets/11223564/20555462/181a3402-b117-11e6-8e88-39a346426efe.jpg)

**Comment by c-ro** [comment]
When I hear 'gloria' I think of Laura Branigan and her affinity for leopard print.
![e2cd036fe91c454cab55a237468b0c3d](https://cloud.githubusercontent.com/assets/8404048/20567750/ef3708e8-b167-11e6-911d-57161ef6bf1b.jpg)
![eac69b15aca6426e80a80a70192c0ffd](https://cloud.githubusercontent.com/assets/8404048/20567814/3a1783a6-b168-11e6-9d6e-29d944893644.jpg)
![a6b8871e26e6a651088c928a00bcc0a4](https://cloud.githubusercontent.com/assets/8404048/20567815/3a197fc6-b168-11e6-8ca4-dbf1198dc2a5.jpg)

**Comment by dvidsilva** [comment]
![image](https://cloud.githubusercontent.com/assets/1588753/20584672/ea8d9e0a-b1a9-11e6-9436-1dbf6451b150.png)

![image](https://cloud.githubusercontent.com/assets/1588753/20584688/128fe7c8-b1aa-11e6-94df-f1444de17566.png)

![image](https://cloud.githubusercontent.com/assets/1588753/20584698/345e7b26-b1aa-11e6-86cb-3b5262e68114.png)

Magic also has some super cool angels.

**Comment by smendoza787** [comment]
Maybe a "flat look" G with some light rays emanating from it? I'll have to mess around with with Photoshop tomorrow !

**Comment by smendoza787** [comment]
![glorialogo](https://cloud.githubusercontent.com/assets/17697950/20637676/c35e66a2-b343-11e6-9c17-7070f2422bab.png)

**Comment by edinchez** [comment]
@smendoza787 it looks exactly like Hexo's logo just in red. I made one that @dvidsilva liked, I'm gonna implement it in the website mockup that I'll make soon and see how it looks, as well as create different versions for different use cases. If you do have another good idea, please don't hesitate to try em out.

**Comment by smendoza787** [comment]
Sorry, excited noob here. I figured I would post it for inspiration. Will do!

**Comment by edinchez** [comment]
Hey sorry, didn't mean to come off rude! Anyway, here's what I have so far; obviously subject to change.

![gloria_logo_2](https://cloud.githubusercontent.com/assets/8266903/20637955/f3c9d7fa-b397-11e6-9bf8-e10753eb2853.png)

**Comment by dvidsilva** [comment]
@smendoza787 I'm gonna use yours and close this. Since is been a while and that was the highest voted. If someone wants to propose more or change it comment here or in slack.
