### ISSUE TITLE
The og repo moved to https://github.com/gloriajs/gloria

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#24]
The code moved to https://github.com/gloriajs/gloria

Please send pull requests, issues and everything there instead.

**Comment by kevdez** [comment]
Repo already moved. I changed most references from `/dvidsilva/gloria` to `/gloriajs/gloria`.

The travis-ci links still have `/dvidsilva/gloria`.

**Comment by dvidsilva** [comment]
Fixed travis.
