### ISSUE TITLE
Create a contributing guide

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#25]
As the project grows the documentation and guides should grow too. 

I wanna start with a basic guide explaning where are the comands, what decisions are being made and why, etc.

**Comment by kevdez** [comment]
I'll start a contributing.md

**Comment by kevdez** [comment]
closing. created here: 9fc7130bec1461899fb68c974efb807bfa29e77b

**Comment by dvidsilva** [comment]
Sweet, i'll link this in the docs and readme
