### ISSUE TITLE
Consider using typescript

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#26]
I really wanna use typescript, is an amazing tool, but I'm not sure what's the best way to use it in a mixed project. Any advice or ideas welcome!

**Comment by IAmAnubhavSaini** [comment]
_And not soon after, we'd move to dart or ruby because those are real languages._ I think ES2015 is better choice.

**Comment by mjhea0** [comment]
Transcompilation are always going to be part of the language. TypeScript forces one to write better code - code that in many cases much faster when it hist the JS runtime engine. If you want to stick with es6, then maybe consider https://flowtype.org/.

**Comment by dvidsilva** [comment]
I found this project, https://github.com/theblacksmith/typescript-require it would make it so typescript files don't need to be compiled. We can save the source files as `.ts` and node will automagically do all it's magic. 

Those familiar with ts can add typescript, those unfamiliar can add regular javascript and it should be okish... 

Still thinking about it, we can see.

**Comment by dvidsilva** [comment]
Oh well, that package doesn't let me casually import all the commands using yargs. :(

**Comment by dvidsilva** [comment]
Nevermind, made it work, made a pull request. #52 It allows the commands to be TS files instead.  

In theory it should work by just changing the extension, like in `skeletal.ts`
