### ISSUE TITLE
Make a pretty website.

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#29]
Competitors like https://hexo.io/ have super cute websites. If we want to crush them and be the best static site generator ever, we need to have a prettier website <3

**Comment by dvidsilva** [comment]
https://gohugo.io/

**Comment by edinchez** [comment]
[Roots](https://roots.cx/) has a pretty website too. I could maybe help with making a cute website.

**Comment by dvidsilva** [comment]
Roots looks pretty nice too, 

I really like this website http://designmodo.github.io/Flat-UI/ and wanted to try something like that, we can look at the other repo, https://github.com/gloriajs/gloria-docs

**Comment by edinchez** [comment]
I feel like that's _so_ 2014. I'll try doing a quick mockup if that's fine and see if you like it.

**Comment by dvidsilva** [comment]
Good point, sure :D let me know, I'll keep working on other features.

**Comment by BeInLife** [comment]
If it will be needed after this week, I can help too :)

**Comment by dvidsilva** [comment]
website is less ugly now, if we want more improvements, go to /gloriajs/gloria-docs
