### ISSUE TITLE
Investigate compatibility with github

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#31]
Jekyll had this magical thing where github would auto compile the source and create the resulting website. It would be nice to have something like that in github. 

A possible solution can be having a commit hook that runs the build command previous to the commit being created? or fails to commit if build hasn't run?

**Comment by mjhea0** [comment]
Travis CI may be a nice way to set it up the build process, but that may be a bit confusing for some. I like the idea of having a basic hook in place to auto deploy to Github upon success. You are adding a  CI/CD process into the codebase. You may want to abstract it out and create a new repo so people can easily add new hosting providers - Heroku, AWS, etc.

**Comment by dvidsilva** [comment]
We could have a deploy on heroku button too. Not sure what's a good way to help others that have no git experience.

**Comment by edinchez** [comment]
I also mentioned this on Slack, you should look into adding compatibility with Netlify, they offer automatic and continuous deployment.

**Comment by dvidsilva** [comment]
We can open other issues for the other providers, but for now I know github works well, our website https://gloriajs.com works out of the box on github, serving out of the folder `docs` in the branch `master`.
