### ISSUE TITLE
Getting 'Maximum call stack size exceeded' error when trying to serve

### ISSUE THREAD

**Issue by edinchez** [gloriajs/gloria#37]
Just installed gloriajs, made a new project using `gloria init` and tried to serve it, and I'm getting the error `Maximum call stack size exceeded`. Tried using the `--dest site` argument too, with no luck.

I'm using Windows 10. Here's a screenshot:

![screenshot](https://i.imgur.com/Lt56qNB.png)

**Comment by dvidsilva** [comment]
I'm booting my windows 10 machine and taking a look.

**Comment by dvidsilva** [comment]
I identified the issue. Looking into it now. It fails when walking the folder.

**Comment by dvidsilva** [comment]
Fixed and created a new release. You can run `npm update -g  gloria` to get the newest version. 

The error was the file separator being used, is diff in windows, and when comparing string paths it failed some checks.
