### ISSUE TITLE
{{url}} doesn't route if a post category is set

### ISSUE THREAD

**Issue by ahmednawar** [gloriajs/gloria#59]
While iterating over `posts`, `{{url}}` only dumps w/e value is set in the page's front-matter which doesn't work when there is a category set. I have to write my href tags as `<a href="{{category}}/{{url}}">` for it to work.

**Comment by dvidsilva** [comment]
Hi, I was looking at the code and that's kinda the expected behavior, unfortunately is not documented properly. 

I changed it to work in the way that you mention, and will add more information in the documentation.
