### ISSUE TITLE
Allow to read data from json files

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#62]
I was writing a page, adding a list of resources, and it was very repetitive to copy each one and create each thing. It would be cool to find a way to include json files in the build process, and add that data to the data passed to the templates.

**Comment by dvidsilva** [comment]
It could be done with a `_data` folder that holds json files, that data can be added to a property called data in the project, and then that data can be accessed in the templates.

The keys for the data can be the name of the json file, to ensure its uniqueness. 

For example:

```
- _data
    - resources.json
    - projects.json
```

Then `resources.json` contains:

```
{
    "list" : [
          "resource1",
          "resource2"
     ]
}
```

And in the templates it could be used as: 

```
  {{#each data.resources}}
        <p>{{this}}
  {{/each}}
```

**Comment by dfrownfelter** [comment]
I'm going to work on this one.
