### ISSUE TITLE
Consider removing typescript-require

### ISSUE THREAD

**Issue by emanuelbuholzer** [gloriajs/gloria#75]
I think we should not be using typescript-require in production. It is unnecessarily heavy, with high memory usage due to the cache being stored in memory. You will also always experience a startup performance penalty as the entire app needs to be compiled on the fly. Furthermore there hasn't been any commits since 9 months.

**Comment by dvidsilva** [comment]
I was experimenting with it, but there seems to be no need for it, I agree. At some point I wanted it to be a typescript project, but there was no want for it on the community. Feel free to create a PR or if I have time i'll do it.

**Comment by emanuelbuholzer** [comment]
I'll create a PR tomorrow removing everything typescript related.
