### ISSUE TITLE
Switch from JSCS to ESLint

### ISSUE THREAD

**Issue by emanuelbuholzer** [gloriajs/gloria#78]
JSCS is end of line and merged with ESLint. Read more here: 
https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.gdvnn8y52

I'd propose switching to ESLint. What are your thoughts?

**Comment by AWulkan** [comment]
ESLint sounds like a good choice to me, especially if JSCS is on the way out.

**Comment by dvidsilva** [comment]
Oh didn't know that, i'd be happy to switch, i can run that tomorrow :D

**Comment by dvidsilva** [comment]
Closed on #92
