### ISSUE TITLE
Code of conduct?

### ISSUE THREAD

**Issue by dvidsilva** [gloriajs/gloria#86]
Is better to have one earlier than not, to avoid problems and etc, and some people don't wanna contribute to projects that don't have one.  Specially important if we want to be a cool community for Jr devs to have a welcoming experience in open source.

For those unfamiliar, a code of conduct is like a set of rules we agree to, to participate in the project.

I prefer something super simple, assuming  people generally have good intentions, and we don't need a zillion paragraphs to tell people to be nice to each other. Comments welcome! 

> Our open source community is a group of adults committed to developing awesome software that Works. Every other concern is subordinate to this goal. As adults, we recognize that there are certain kinds of childish behavior that are unwelcome in our community. We respond to such behavior by generally ignoring and/or—in extreme cases—making sport of, individuals who engage in such behavior.  We accept everyone's contributions, we don't care if you're liberal or conservative, black or white, straight or gay, or anything in between! In fact, we won't bring it up, or ask. Those conversations have no place in the repo, issues or slack. Repeat offenders will probably get banned. If you need to complain about someone's behavior or report something never do it in public, message the maintainers on slack.

**Comment by AWulkan** [comment]
Looks good, but I would not put so much emphasis on being an adult. I know a lot of teenagers that are awesome at programming and active in open source communities.

**Comment by dvidsilva** [comment]
Fair point, something like this?

> Our open source community is a group of people committed to developing awesome software that Works. Every other concern is subordinate to this goal. We recognize that there are certain kinds of childish behavior that are unwelcome in our community. We respond to such behavior by generally ignoring and/or—in extreme cases—making sport of, individuals who engage in such behavior. We accept everyone's contributions, we don't care if you're liberal or conservative, black or white, straight or gay, or anything in between! In fact, we won't bring it up, or ask. Those conversations have no place in the repo, issues or slack. Repeat offenders will probably get banned. If you need to complain about someone's behavior or report something never do it in public, message the maintainers on slack.

**Comment by AWulkan** [comment]
Ship it.

**Comment by AWulkan** [comment]
We'll need to change it later to include robots as well though, but I don't think any AI will become sentient this decade, so we're good for now.

**Comment by dvidsilva** [comment]
Added on commit https://github.com/gloriajs/gloria/commit/31ded64e373591e921b8419f15d16fe2ddc463f6

**Comment by AWulkan** [comment]
Nice, so if there is no category metadata it will simply not fill in any category in the permalink?

So it would go from this:
`example.com/blog/undefined/post-title`
to this:
`example.com/blog/post-title`

Correct?
